In [1]:
import numpy as np
from numpy import nan

from tabulate import tabulate
import random
from itertools import zip_longest
from collections import namedtuple
from stack import Stack
from actions import Moove, Action, List_actions
from utils_class import EpsilonGreedy, ReplayMemory, Agent, Experience
from DQN import DQNAgent
from env import Env 

%load_ext autoreload
%autoreload 2


2022-06-03 07:35:16.184244: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-03 07:35:16.184267: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
STACK_SIZE = 10

EPISODE = 2
CAPACITY = 100_000
BATCH_SIZE = 3
MIN_REPLAY_MEMORY_SIZE = 100

DECAY = 0.001
START_EPSILON = 1
MIN_EPSILON = 0.15
TARGET_UPDATE = 10

ACTION_REWARD = -1
INVERSE_ACTION_REWARD = -5
FINISH_REWARD = 100

LEARNING_RATE = 0.1
DISCOUNT = 0.95
GAMMA = 0.99


In [6]:
size = 10
env = Env(size)

In [5]:
for episode in range(EPISODE):
    
    env.reset(STACK_SIZE)
    state = env.state()
    # env.print_state()
    
    # while not (env.state == 'done'):
    for i in range(2):
        action = env.choose_action()
        reward = env.reward()
        next_state = env.state()
        experience = env.create_experience(state, action, next_state, reward)
        env.replaymemory.push(experience)
        # env.print_experience(experience)
        state = next_state

        if env.replaymemory.can_provide_sample(BATCH_SIZE):
            experiences = env.replaymemory.get_sample(BATCH_SIZE)
            states, actions, next_states, rewards = env.replaymemory.extract_value(experiences)
            
            
    
    

STATES [[[49. 31. 75. 21. 70. 27. 11. 43. 35.  3.]
  [nan nan nan nan nan nan nan nan nan nan]]

 [[ 8.  4. 64. 65. 25. 28. 49. 72. 52. 40.]
  [nan nan nan nan nan nan nan nan nan nan]]

 [[ 3. 49. 31. 75. 21. 70. 27. 11. 43. 35.]
  [nan nan nan nan nan nan nan nan nan nan]]]
STATES [[[83. 23.  6. 37. 69. 41. 80. 44. 12. 96.]
  [nan nan nan nan nan nan nan nan nan nan]]

 [[83. 23.  6. 37. 69. 41. 80. 44. 96. 12.]
  [nan nan nan nan nan nan nan nan nan nan]]

 [[ 4. 64. 65. 25. 28. 49. 72. 52. 40.  8.]
  [nan nan nan nan nan nan nan nan nan nan]]]
STATES [[[83. 23.  6. 37. 69. 41. 80. 44. 96. 12.]
  [nan nan nan nan nan nan nan nan nan nan]]

 [[83. 23.  6. 37. 69. 41. 80. 44. 12. 96.]
  [nan nan nan nan nan nan nan nan nan nan]]

 [[ 3. 49. 31. 75. 21. 70. 27. 11. 43. 35.]
  [nan nan nan nan nan nan nan nan nan nan]]]
STATES [[[62. 59. 29. 37.  1. 30. 84. 33. 56. 19.]
  [nan nan nan nan nan nan nan nan nan nan]]

 [[83. 23.  6. 37. 69. 41. 80. 44. 12. 96.]
  [nan nan nan nan nan nan n

In [11]:
# env.print_stack()
# env.moover.push_b()
# env.choose_action()
env.current_action = 0
env.take_actions()
env.create_experience()
env.replaymemory.push(env.experience)
env.current_action = 1
env.take_actions()
env.create_experience()
env.replaymemory.push(env.experience)
env.current_action = 0
env.take_actions()
env.create_experience()
env.replaymemory.push(env.experience)
env.take_actions()
env.create_experience()
env.replaymemory.push(env.experience)
# print(env.experience)
env.print_state()


---State t---
-A-	-B-
___________	
|52.0	4.0|
|15.0	92.0|
|48.0	nan|
|68.0	nan|
|8.0	nan|
|89.0	nan|
|78.0	nan|
|60.0	nan|
|nan	nan|
|nan	nan|
___________	


In [6]:
env.replaymemory.get_sample(4)

[Experience(state=array([[nan, 13., 27., 84., 58., 93., 67., 35., 11., 71.],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, 26.]], dtype=float32), action=1, next_state=array([[13., 27., 84., 58., 93., 67., 35., 11., 71., 26.],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]], dtype=float32), reward=-6),
 Experience(state=array([[13., 27., 84., 58., 93., 67., 35., 11., 71., 26.],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]], dtype=float32), action=0, next_state=array([[nan, 13., 27., 84., 58., 93., 67., 35., 11., 71.],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, 26.]], dtype=float32), reward=-1),
 Experience(state=array([[13., 27., 84., 58., 93., 67., 35., 11., 71., 26.],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]], dtype=float32), action=0, next_state=array([[nan, 13., 27., 84., 58., 93., 67., 35., 11., 71.],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, 26.]], dtype=float32), reward=-6),
 Experience(state=array([[nan, 

In [7]:
env.replaymemory.print_history(BATCH_SIZE)

Actions : 0 	 Reward : -1
Actions : 1 	 Reward : -6
Actions : 0 	 Reward : -6
Actions : 0 	 Reward : -1
